# Generated by Django 3.2 on 2021-04-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_directory_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
