# Generated by Django 3.2 on 2021-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
