# Generated by Django 3.2 on 2021-04-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_directory_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesection',
            name='sectionBegin',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='filesection',
            name='sectionLines',
            field=models.IntegerField(default=-1),
        ),
    ]
