# Generated by Django 3.2 on 2021-04-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210428_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesection',
            old_name='sectionLines',
            new_name='sectionEnd',
        ),
        migrations.AlterField(
            model_name='filesection',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='statusdata',
            name='statusData',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
